### PR TITLE
Added web demo

### PR DESCRIPTION
**Pull request by redblobgames**
Display many but not all variants of the GLSL noise shader library
functions, including export to a shadertoy-compatible format for
further experimentation.

### CODE REVIEW

**Comment by redblobgames** [comment]
Github Pages can display this html from the repository without needing a separate site for hosting the pages. I enabled that and tested the pages here: https://redblobgames.github.io/webgl-noise/webdemo/ . The corresponding URL in your repository (e.g. https://stegu.github.io/webgl-noise/webdemo/) could be something we link from the wiki or the README.

**Comment by stegu** [comment]
> Github Pages can display this html from the repository without needing a
separate site for hosting the pages.

Could you please tell me how to do that, or point me to the instructions? I
can't find that option. I granted your pull request. Thank you very much!

  /Stefan G

**Comment by stegu** [comment]
Nevermind, there was a slight delay before Github actually published the pages after I changed the settings. It works like intended now.

**Comment by redblobgames** [comment]
Great! Suggestion: in the About section of https://github.com/stegu/webgl-noise if you click the "gear" icon there's an entry for the project URL. That'd be another possible place to link to http://stegu.github.io/webgl-noise/webdemo/

**Comment by stegu** [comment]
I'm not seeing that URL option, sorry. I did make the demo link much more
prominent in the single wiki page, though.

**Pull request merged**
